sudo: false
language: java
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
install: true
script: gradle build
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
