name: Build, Test, and Deploy

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:

jobs:
  call-build:
    uses: KyoriPowered/.github/.github/workflows/shared-ci.yaml@trunk
    with:
      runtime_version: 17
    permissions:
      actions: write
      contents: write
    secrets: inherit
